instruction_dir:  "C:\\Users\\Operator\\Desktop\\Michael\\HTE photocatalysis project\\tests for writing of csv from AutoSuite"
firesting_port: 
  name: "USB Serial Port"
lamp_port: 
  name: "USB-SERIAL CH340"
arduino_port: 
  name: "Arduino"
sleep_time: 0
log_dir:  "C:\\Users\\Operator\\Documents\\photcat_hte\\photocat-hte\\experiments\\logs"
chemspeed_working_dir:  "C:\\Users\\Operator\\Desktop\\Michael\\HTE photocatalysis project\\tests for writing of csv from AutoSuite"