instruction_dir: /path/to/instructions
firesting_port: 
  port: "COM8"
  name: "USB Serial Port"
lamp_port: 
  port: "COM4"
  name: "USB-SERIAL CH340"
sleep_time: 1
log_dir: /path/to/logs
chemspeed_working_dir: /path/to/chemspeed